### PR TITLE
Add property diagram

### PR DESCRIPTION
**Pull request by gkellogg**
Done using Omnigraffle.

/cc @iherman

### CODE REVIEW

**Comment by iherman** [comment]
@gkellogg I have just made an alternative diagram to this one, though inspired by yours... I had several issues with the diagram you proposed
- The SVG file does not scale. This seems to be a problem with all the SVG editors or converters I know: they produce a non-scalable SVG file (which is crazy, SVG stands for _scalable_ vector graphics!). It requires a manual change in the XML file to make it right.
- Your diagram is very 'vertically' oriented and therefore does not really use space well and makes it difficult to get an overall picture (at least in my view)
- There were also some connecting lines missing

So I have branched _from this branch_ and produced an alternative diagram in:

https://rawgit.com/w3c/csvw/metadata-diagrams-ivan/metadata/properties.svg

Note that I have also added a `notes` property in the Table Group, I think we agreed that would be added as well.

WDYT

/Cc @6a6d74 @JeniT

**Comment by 6a6d74** [comment]
@iherman - I notice that some of your line endings are arrows; others are squares. Prob should all be arrows. I am also just creating a mockup of a better layout for the diagram ...

**Comment by iherman** [comment]
> On 24 Mar 2015, at 14:00 , Jeremy Tandy notifications@github.com wrote:
> 
> @iherman - I notice that some of your line endings are arrows; others are squares. Prob should all be arrows. I am also just creating a mockup of a better layout for the diagram ...

That was intentional, but maybe I should add an additional legend; I took this from Gregg's diagrams. The squares belong to array properties, and what they mean to show is that the given property does not directly refer to an object (eg, resources do not refer to a Table description but an array thereof). We may decide to remove that thing if we feel that we do not want this differentiation.

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by 6a6d74** [comment]
@iherman - thanks for clarification. See revised layout (without cross-overs) ... using the same arrow/square connector ends. (sadly it's a mock up made from screen grabbing bits of your image :-) )
metadata-properties-schematic 001

**Comment by 6a6d74** [comment]
(i didn't include the legend - this needs to be inserted somewhere)

**Comment by 6a6d74** [comment]
One other thing - do you think it's worth including a line for Common Properties in TableGroup and Table?

**Comment by iherman** [comment]
That looks o.k. to me, although I would take it exactly as is; the previous version had some sort of a closer relationship reflected in the position between Table Groups and Table description, this version, sort of, puts dialects and transformation on equal footing, whereas they are not the most important blocks... but I will play with that approach and update my files accordingly. Do not do any merge yet..

**Comment by iherman** [comment]
There is no specification for any common property in this specification, so I am not sure how to add those there... I would leave those aside for now.

**Comment by 6a6d74** [comment]
> the previous version had some sort of a closer relationship reflected in the position between Table Groups and Table description, this version, sort of, puts dialects and transformation on equal footing

True. I've tried to keep the Group > Table > Schema > Column > Inherited Property (on Cell) cascade tho.

**Comment by gkellogg** [comment]
This kind of layout is definitely much better than mine.

 I agree that dialect and transformations should be less prominent.

Common properties could be a cell with a 0..\* superscript perhaps _common:properties_.

**Comment by iherman** [comment]
Can you guys look at the new layout, based on @6a6d74 's sketch?

/Cc @gkellogg @6a6d74

**Comment by 6a6d74** [comment]
+1 (belatedly) to the merge. Thanks both @iherman and @gkellogg

**Pull request closed without merging**
