### PR TITLE
Issue 588 length constraint

### PR DESCRIPTION
**Pull request by gkellogg**

### CODE REVIEW

**Comment by iherman** [comment]
#591 is indeed settled through this, thanks!

**Comment by JeniT** [comment]
@gkellogg When you pack editorial changes into issue-based pull requests it makes them hard to review because the few relevant changes are hidden by the large number of irrelevant ones. (I also disagree that the punctuation that's been added in this case is "correct" but it's not a major issue so I'm not going to get into an edit war over it.)

**Comment by JeniT** [comment]
Just made a bit of a change in the wording to make it clear that we're just reiterating what it says in XML Schema Datatypes spec. Merge if you're happy @gkellogg.

**Comment by gkellogg** [comment]
@JeniT, when changes overlap across PRa, it leads to conflicts that require even more work to resolve; they were done in separate commits, so the main changes to see were in the first commit. The amount of time it takes to close PRs doesn't make it reasonable to wait for them to be closed before proceeding with the editorial changes, otherwise, I would agree

The list line ending changes are consistent with our previous resolution. I don't care what our policy is, so long as we use it consistently.

**Pull request merged**
