### PR TITLE
Added reference to the annotation/metadata property changes

### PR DESCRIPTION
**Pull request by iherman**
I Added some text to the change sections of the metadata, csv2rdf and csv2json documents. I am not sure whether there was any change in the model document, though.

### CODE REVIEW

**Comment by iherman** [comment]
This is relevant to issue #646

**Comment by gkellogg** [comment]
+1 good to merge for me.

**Comment by iherman** [comment]
Anything to add for the model document? As far as I remember that change did affect that document significantly, but I just want to cross check...

**Comment by gkellogg** [comment]
There may have been some cleanup and clarifications, but noting notable IIRC.

**Comment by iherman** [comment]
This fixes #646

**Pull request merged**
