### PR TITLE
Hide details

### PR DESCRIPTION
**Pull request by iherman**
This is a running version of the 'hiding' version of csv2*. There is a separate js file in the directory and the index files are modified.

### CODE REVIEW

**Comment by iherman** [comment]
This version does not yet take care of the print version (ie, to produce a full print), that is for later when we find out how to do that:-)

**Comment by iherman** [comment]
@6a6d74, I let you decide whether you want to merge the pull request, or whether you want to do some other changes first.

**Comment by 6a6d74** [comment]
@iherman - you'll see I've made some small optimisations:
- missing `script` tag closure, messed up the Respec rendering etc.) 
- moved `hide.js` up one level so it sits alongside `local-biblio.js` and can be shared between csv2json and csv2rdf

Other than that, it looks good in the _browser_.

However, having tried to print the both documents (admittedly only to PDF) the annotations are not shown by default. I am inclined to agree with the earlier comments from @gkellogg about having annotations shown by default when you try to print.

I guess this turned out to be hard?

**Comment by iherman** [comment]
@6a6d74 : 
- I know about the print issue, and I have found some references to solve it (@gkellogg also referred to it), but I have not had the time of dealing with it yet. I think it should be o.k. to publish the document as it is now in April and solve the issue by the time of the LCCR (unless I solve it by then). 
- moving the hide.js up is not a good idea:-( The problem is that this script should be part of the /TR publication (as opposed to the references file), so it should be in the directory where the core document is. That is why I had to duplicate it and keep it in the same directory.
- sorry about the missing closing script element:-)

**Comment by 6a6d74** [comment]
@iherman ... OK- I've reverted the move of `hide.js`.

It occurs to me that you might have the same issue with `local-biblio.js` which is also "up one level" and shared across files ... and the examples too. 

I've created ISSUE #380 to remind us to revisit the print-mode behaviour.

Merging now ...

**Comment by gkellogg** [comment]
Actually, when the ReSpec source is saved to Overview.html, the local-biblio.js isn't referenced any more. The issue is for when docs are published to /TR.

**Comment by iherman** [comment]
Exactly. That is why we can share the bibliography file on the repo but we can't do it with hide.js.

**Comment by 6a6d74** [comment]
Ah. It all becomes clear :-) ... presumably the examples that are shared across documents are _also_ embedded when a snapshot is taken too?

**Comment by iherman** [comment]
> On 20 Mar 2015, at 08:05 , Jeremy Tandy notifications@github.com wrote:
> 
> Ah. It all becomes clear :-) ... presumably the examples that are shared across documents are also embedded when a snapshot is taken too?

Indeed. Respec takes care of that, so when we generate the 'pure' HTML version all those inclusions, including the references, are done. But the hiding stuff is different.

ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Pull request merged**
