### PR TITLE
reworked bidi display recommendations

### LINKED ISSUE #620: determining cell text direction
the 'base direction' of a string is crucial to correct display when dealing with bidirectional text (see http://www.w3.org/International/articles/inline-bidi-markup/uba-basics for an explanation of why). The base direction can be determined by metadata (such as the dir attribute in html) or by testing the data (typically identifying the direction of the first strong character).  The latter approach does not always produce the correct base direction, eg. where latin characters appear at the start of a bidirectional string.

as far as i can tell, the overall 'direction' annotation for the table, sets the direction of columns on display, but is not used to set the default direction of text in cells.  

6.4 Parsing Cells says that the cell annotation for text direction takes its value from the column annotation for text direction.

it seems, then, that it is possible to indicate that the direction of all cells in a particular column should be, say, rtl, by specifying direction for that column.

it's not clear to me whether the last paragraph in 6.5.1 is contradicting this by suggesting that the presence of strong characters in the cell will cause the UBA's first-strong algorithm to kick in, or simply that the contents of the cell will be treated as normal by the UBA, given the base direction set by the 'text direction' cell annotation. I'm particularly unclear, since the preceding sentence seems to be applying different rules for strings with no strong characters, and is followed by 'However...'.

here are some thoughts/issues/questions:

i would have thought that it would be easier to use the direction annotation of the table to establish the default base direction for cell values, rather than only being able to specify it per column. (Then it would be analogous to the dir attribute on the html element.)

i also think it may be useful sometimes to specify the direction for a given row.

if the direction of a table is not set, or the direction is set to auto/default, then i would expect that the first-strong algorithm would be applied to cells to determine the base direction.

on the other hand, if the direction of a cell is specified by an annotation, then the cell should probably take its direction from that.

am i correct in thinking that it is also possible to use metadata to set the direction for a particular cell?  If so, then the algorithm should not overwrite that with the value in the column annotation.

### PR DESCRIPTION
**Pull request by JeniT**
Including updating the applicable values for cell text direction to
include `auto` and `inherit`.

Intended to fix #620 - @r12a @matial please could you review the changes?

### CODE REVIEW

**Comment by matial** [comment]
Sorry if I am finicky, but I still have  some problems with the text, in fact , 3 problems.

Problem 1. Text direction at the table level

I think that there is overload on the text direction annotation at the table level, because it has one value while we need 2 pieces of information.
a) Ordering of the columns for display (starting from the left or from the right).
b) Default value for the text direction annotation of the cells within the table.
While it will often be the case that columns proceed from left to right and cells need a LTR base direction, or columns proceed from right to left and cells need a RTL base direction, this may not always be the case. In particular, we may want the cell direction to default to AUTO, but what would AUTO mean for column ordering? 
If table direction stays as an overloaded value, then
- it should be made clear what a value of AUTO means for column ordering (e.g. LTR).
- If a value of LTR or RTL is specified at the table level, but a different value is needed for some or all columns (e.g. AUTO), then the text direction will need to be specified for all such columns. A bit tedious, but possible.

Problem 2. Relationship between text direction annotation and UBA algorithm

The current text says: 
[quote]if a cell contains no characters with a strong type (if it's a number or date for example) then the way the cell is displayed should be determined by the text direction annotation of the cell. However, when the cell contains characters with a strong type (such as letters) then they should be displayed according to the Unicode Bidirectional Algorithm as described in [[!BIDI]].
[end of quote]
In this text, a text direction of LTR or RTL is only applied to cells without any strong character,
This does not follow generally agreed bidi usage, e.g. in HTML. Usually, if the direction is specified as AUTO, then the first-strong-character algorithm is applied. If there is no strong character in the text, then a default will be applied, usually LTR (but it could make sense to default to the explicit text direction of a higher component).
If the direction is specified as LTR or RTL, then it must be applied without consideration to the content of the cell, so LTR/RTL values for text direction mean that the first-strong algorithm will not be applied for the current cell, column or table.

Problem 3. Hierarchy Cell < Column < Table

The current text says: 
[quote]If the cell textDirection property in metadata has the value "inherit", the cell text direction annotation for a cell inherits its value from the table direction annotation on the table.
[end of quote]
It seems to me that the cell direction should be inherited from the column direction of the including column, which itself may be inherited from the table direction, or respecified independently from the table direction.

**Comment by matial** [comment]
Here is the comment that I submitted to https://github.com/w3c/csvw/pull/638

Sorry if I am finicky, but I still have some problems with the text, in fact, 3 problems.

Problem 1. Text direction at the table level

I think that there is overload on the text direction annotation at the table level, because it has one value while we need 2 pieces of information.

a) Ordering of the columns for display (starting from the left or from the right).

b) Default value for the text direction annotation of the cells within the table.

While it will often be the case that columns proceed from left to right and cells need a LTR base direction, or columns proceed from right to left and cells need a RTL base direction, this may not always be the case. In particular, we may want the cell direction to default to AUTO, but what would AUTO mean for column ordering? 

If table direction stays as an overloaded value, then
- It should be made clear what a value of AUTO means for column ordering (e.g. LTR).
- If a value of LTR or RTL is specified at the table level, but a different value is needed for some or all columns (e.g. AUTO), then the text direction will need to be specified for all such columns. A bit tedious, but possible.

Problem 2. Relationship between text direction annotation and UBA algorithm

The current text says: 

[quote]if a cell contains no characters with a strong type (if it's a number or date for example) then the way the cell is displayed should be determined by the text direction annotation of the cell. However, when the cell contains characters with a strong type (such as letters) then they should be displayed according to the Unicode Bidirectional Algorithm as described in [[!BIDI]].

[end of quote]

In this text, a text direction of LTR or RTL is only applied to cells without any strong character,

This does not follow generally agreed bidi usage, e.g. in HTML. Usually, if the direction is specified as AUTO, then the first-strong-character algorithm is applied. If there is no strong character in the text, then a default will be applied, usually LTR (but it could make sense to default to the explicit text direction of a higher component).

If the direction is specified as LTR or RTL, then it must be applied without consideration to the content of the cell, so LTR/RTL values for text direction mean that the first-strong algorithm will not be applied for the current cell, column or table.

Problem 3. Hierarchy Cell < Column < Table

The current text says: 

[quote]If the cell textDirection property in metadata has the value "inherit", the cell text direction annotation for a cell inherits its value from the table direction annotation on the table.

[end of quote]

It seems to me that the cell direction should be inherited from the column direction of the including column, which itself may be inherited from the table direction, or respecified independently from the table direction.

## 

Shalom (Regards),  Mati

**Comment by JeniT** [comment]
@matial thanks for the review. Let me go through your points. I have included links to the proposed new text in the hope that ensures we are talking about the same text.
1. You say that the "text direction annotation at the table level" is overloaded. But there is no **text direction** annotation at the table level. I think that you might be confusing the annotations in the model with the properties in the JSON metadata file, but even then I don't think that there is overloading. Let me summarise:

There are two relevant annotations:
- [**direction** annotation on tables](https://rawgit.com/w3c/csvw/issue-620-cell-text-direction/syntax/index.html#dfn-table-direction), which can be one of `ltr`, `rtl` or `auto` and determines the direction of the columns in the table
- [**text direction** annotation on cells](https://rawgit.com/w3c/csvw/issue-620-cell-text-direction/syntax/index.html#dfn-cell-text-direction), which can be one of `ltr`, `rtl` or `auto` and determines the direction of the text within the cell

These are independent and are used as described in the section on [Bidirectional Tables](https://rawgit.com/w3c/csvw/issue-620-cell-text-direction/syntax/index.html#bidirectional-tables). It is possible for a table's **direction** (determining column order) to be RTL and for a particular cell to have the **text direction** (determining text direction within the cell) to be LTR. It is possible for the table's **direction** to be LTR and for the **text direction** of a cell to be automatically determined based on the contents of the cell.

The **direction** and **text direction** annotations are set using the [`tableDirection`](https://rawgit.com/w3c/csvw/issue-620-cell-text-direction/metadata/index.html#tableDirection) and [`textDirection`](https://rawgit.com/w3c/csvw/issue-620-cell-text-direction/metadata/index.html#cell-textDirection) properties in the JSON metadata for a CSV file. By default, `textDirection` is set to `inherit` which means that (presuming no overrides at the column level), every cell's **text direction** will be the same as the table's **direction**. So if you just specify:

```
"tableDirection": "rtl"
```

then the columns should be displayed RTL and the text in cells also be displayed RTL. It is equally possible to specify:

```
"tableDirection": "rtl",
"textDirection": "auto"
```

which means the columns should be displayed RTL and the contents of cells displayed based on the first strong character within each cell. It is equally possible to specify `textDirection` at the level of individual columns.

You say "It should be made clear what a value of AUTO means for column ordering (e.g. LTR).". The [text](https://rawgit.com/w3c/csvw/issue-620-cell-text-direction/syntax/index.html#bidirectional-tables) says:

> If direction is auto then tables should be displayed with attention to the bidirectionality of the content of the file. Specifically, the values of the cells in the table should be scanned breadth first: from the first cell in the first column through to the last cell in the first row, down to the last cell in the last column. If the first character in the table with a strong type as defined in [BIDI] indicates a RTL directionality, the table should be displayed with the first column on the right and the last column on the left. Otherwise, the table should be displayed with the first column on the left and the last column on the right. Characters such as whitespace, quotes, commas, and numbers do not have a strong type, and therefore are skipped when identifying the character that determines the directionality of the table.

I am not sure how to make it clearer than this, but please do make suggestions, particularly if you think this behaviour is the wrong behaviour.

You also say "If a value of LTR or RTL is specified at the table level, but a different value is needed for some or all columns (e.g. AUTO), then the text direction will need to be specified for all such columns. A bit tedious, but possible." I hope the examples above demonstrate that it is possible to set a direction of LTR or RTL at the table level _and_ AUTO at the cell level. Perhaps it's wrong to make `inherit` the default for the `textDirection` property and it should be `auto` instead?
1. You quote some text that appears in the current editor's draft but does not appear within the suggest amendments in this pull request. Please could you take a look at the suggested text in this pull request --- here is the link: [Bidirectional Tables](https://rawgit.com/w3c/csvw/issue-620-cell-text-direction/syntax/index.html#bidirectional-tables) --- and see if the revised text that I have suggested in this pull request actually meets your requirements.
2. You say "It seems to me that the cell direction should be inherited from the column direction of the including column, which itself may be inherited from the table direction, or respecified independently from the table direction." I entirely agree and this is exactly possible. You can specify the `textDirection` (ie the direction of text in cells) at the table level or at the level of individual columns. Wherever you specify it, the cells in scope will be given the appropriate **text direction** annotation. So for example:

```
"tableDirection": "rtl",
"tableSchema": {
  "columns": [{
    "name": "numbers",
    "textDirection": "ltr"
  }, {
    "name": "text"
  }]
}
```

Here, the table will be displayed with the columns RTL. The `numbers` column will have its contents displayed LTR. The cells in the `text` column have the default `textDirection` of `inherit` which means the **text direction** annotation on the cells in that column will be the same as the **direction** of the table, namely RTL.

If you can suggest any improvements to the text that would help make this clearer, let me know. Similarly if you have any further comments on the revised text. Please also let me know if you are content with the changes that are incorporated into this PR, so that we can merge it and publish.

**Comment by r12a** [comment]
@JeniT i suspect that it may help to make things clearer to use the term **table direction** rather than **direction**  when referring to the table-level information (this distinction is already made in the JSON naming you show above, and it would also help to be consistent with that).  [I'll use 'table direction' to refer to 'direction' at the table level in the rest of this comment for clarity.]

As i understand it, the _prime_ function of the **table direction** annotation is to indicate the order of columns, as mentioned in https://rawgit.com/w3c/csvw/issue-620-cell-text-direction/syntax/index.html#dfn-table-direction, _but_ as you mention towards the end of the comment just above, it can also be used to derive the default base direction for cells if no direction has been specified for them at the cell or intervening column level (this is of course what Hebrew or Arabic users will be relying on, since it avoids having to declare the same direction many times). It may help to mention the inheritance possibility at the link i just mentioned for clarity. In section 6.5.1, the sentence "The direction annotation on the table provides information about the desired display of the table." already implies that (intentionally or not) due to the ambiguity of the wording 'display of the table'.

In the new text at https://rawgit.com/w3c/csvw/issue-620-cell-text-direction/metadata/#cell-textDirection  describing the inherited annotation text direction, you say "or in the direction inherited from the <a href="http://w3c.github.io/csvw/syntax/#dfn-table-direction" class="externalDFN">direction</a> annotation of the <a href="http://w3c.github.io/csvw/syntax/#dfn-table" class="externalDFN">table</a>".  Should this not say 'inherited from the [table] direction annotation of the table, _or the text direction annotation of the column it belongs to, if such an annotation has been set_.", or words to that effect?

Where the new text in 6.5.1 says "then the cell content should be displayed right-to-left", it may be better (more accurate) to say "then the base direction for the cell content should be set to right-to-left", and similar for like text.  (If the direction happens to be set to rtl, but the cell content is just a number, it will actually be displayed ltr regardless, since all numbers are.)

am i correct to think that 10.4.5.1.1 and 10.5.4.2 sets the default text direction of a cell to auto?  If so, i think this may be problematic, since i don't see how any cells would ever inherit any base direction set at the column or table direction in that case.  Should this not say "text direction set to inherit"?  That would seem to fit with the implications of the note in 6.5.1.

Text has to have a base direction. If a cell has no **text direction** annotation, and it's **text direction** value is treated as inherit, and there's no **text direction** value set on the column, then the cell will need to inherit the value from the **table direction**.  If this **table direction** value is not declared, it is necessary to say in the spec what the default would be – typically LTR, although one could perhaps argue for auto. Am i right to think that section 8, step 1 does in fact set a default value of auto for the **table direction**?

**Comment by JeniT** [comment]
Thanks @r12a, I particularly appreciate the time that you (and the rest of the I18N group) are taking to get us to the right place on this, and particularly your speedy replies given our time constraints.

I have now:
- renamed the table's **direction** annotation to be called **table direction**
- noted in the Model document that the **table direction** may be used to derive the **text direction** annotation
- clarified the wording around what **table direction** affects, to say it states "the desired display of the columns in the table" rather than "the desired display of the table"
- clarified the way in which inherited properties such as `textDirection` work, to make it clear that these properties are used to provide values for annotations both at the column and at the cell level, and that they can be inherited from the descriptions of table groups, tables and schemas; please read the introductory text at https://rawgit.com/w3c/csvw/issue-620-cell-text-direction/metadata/#inherited-properties as well as the description of the `textDirection` property within that section --- this isn't exactly what you asked for but I hope it addresses the underlying concern
- rephrased relevant text to say "then the base direction for the cell content should be set to ..." as suggested

You ask about the steps in the (non-normative) CSV parsing algorithm at 10.4.5.1.1 and 10.5.4.2 and highlight that these set the **text direction** annotations to `auto`. These annotations are overridden by any supplied metadata so they are only relevant when there is no other information available. Note also that at step 1 of that parsing algorithm, the **table direction** annotation is also set to `auto`, so the effect is exactly as if a `textDirection` property had been supplied with the value `inherit`.

The default for the **table direction** and **text direction** annotations, lacking any other information, is currently `auto`. If this should be `ltr` instead then I can make the relevant changes to the default `tableDirection` property and to the parsing algorithm in the Model document. I don't have a strong feeling either way on whether this should be `ltr` or `auto` and defer to your expertise.

**Comment by r12a** [comment]
afaict lgtm

the question of whether the default should be auto or ltr, i am not clear on either.

**Comment by JeniT** [comment]
Thanks @r12a - we'll stick with the `auto` default in that case. @gkellogg this is ready for merge now.

**Pull request merged**
