### PR TITLE
CR snapshots of metadata and syntax docs.

### PR DESCRIPTION
**Pull request by gkellogg**

### CODE REVIEW

**Comment by iherman** [comment]
Great, thanks!

Although… there is still a pending pull requests[1] that actually affect all documents. But it should be easy to update things.

@gkellogg, have you run the documents through the pubrules checker and html validator and link checker? I can try to do that tomorrow if needed.

@JeniT, what is the fate of the missing PR[1] I presume it is waiting on @r12a's response, right?

[1] https://github.com/w3c/csvw/pull/638

> On 06 Jul 2015, at 18:07 , Gregg Kellogg notifications@github.com wrote:
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/w3c/csvw/pull/656
> 
> Commit Summary
> 
>   • CR snapshots of metadata and syntax docs.
> File Changes
> 
>   • A publishing-snapshots/CR-metadata/Overview.html (2478)
>   • A publishing-snapshots/CR-metadata/diff-20150416.html (23879)
>   • D publishing-snapshots/CR-metadata/index.html (104)
>   • A publishing-snapshots/CR-syntax/Overview.html (2808)
>   • A publishing-snapshots/CR-syntax/diff-20150416.html (31463)
>   • D publishing-snapshots/CR-syntax/index.html (104)
>   • M syntax/index.html (2)
> Patch Links:
> 
>   • https://github.com/w3c/csvw/pull/656.patch
>   • https://github.com/w3c/csvw/pull/656.diff
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
I thought it a good idea to pre-flight these and regenerate later.

Yes, they pass pub-rules and link checkers with expected results.

**Comment by iherman** [comment]
Super!

Ivan

---

Ivan Herman
Tel:+31 641044153
http://www.ivan-herman.net

(Written on mobile, sorry for brevity and misspellings...)

**Comment by gkellogg** [comment]
See https://github.com/w3c/csvw/pull/658.

**Pull request merged**
