### PR TITLE
Issue 446 inherited property annotations

### LINKED ISSUE #446: Inherited property annotations on columns
There's currently inconsistency in which [inherited properties](http://w3c.github.io/csvw/metadata/#inherited-properties) are copied onto [columns](http://w3c.github.io/csvw/syntax/#columns) as annotations: only `datatype` becomes an annotation, and not, for example, `lang` or `null` or `default` or `separator`.

I think either all these properties should become core annotations on columns, or none.

Further, for the purposes of aiding data entry, I think it would be useful for columns to have all the inherited properties as core annotations. Note that the [URI template properties](http://w3c.github.io/csvw/metadata/#uri-template-properties) would have to turn into annotations whose values were URI template strings, not URIs.

### PR DESCRIPTION
**Pull request by gkellogg**
This fixes #446.

@JeniT, this can probably be resolved before the telecon, as I don't think it's controversial. You may want to fix any annotation definitions that don't align with your thoughts.

### CODE REVIEW

**Comment by JeniT** [comment]
I think the metadata document needs to be updated to ensure that the new annotations are populated correctly. @gkellogg do you want to have a go on that or shall I?

**Comment by gkellogg** [comment]
This should be ready now, @JeniT. Note that we may want to remove `ordered` and `table direction` annotations on the cell as they duplicate those on the column. If so, we need to update the metadata definitions of those properties too.

**Comment by gkellogg** [comment]
... Alternatively, not create column annotations, and just use the cell annotations.

**Comment by gkellogg** [comment]
Merging to simplify PR #469, but will keep issue #457 open for review.

**Pull request merged**
