### PR TITLE
Introduced validation modes

### LINKED ISSUE #14: Open and/or Closed validation requirement
[R-CsvValidation](http://w3c.github.io/csvw/use-cases-and-requirements/index.html#R-CsvValidation)

David Booth suggests:

"It sounds like the R-CsvValidation requirement may need to be split into two separate validation requirements:

R-CsvOpenValidation: Does the data in the CSV conform to the metadata, ignoring inapplicable metadata? For example, is every column in the CSV described by some metadata?

R-CsvClosedValidation: Does the metadata describe anything that does NOT appear in the CSV?

I suppose if the metadata had a notion of optional columns then both of these cases could be covered at once."

However, at this point the use cases only appear to relate to the closed validation case. Do we need another use case to support open validation?

### PR DESCRIPTION
**Pull request by JeniT**
fixes #14 

I've ended up introducing four validation modes:
- `closed` if the columns in a schema and the data file must match
- `extension` if the data is allowed to contain more columns than the schema specifies
- `restriction` if the data is allowed to contain fewer columns than the schema specifies
- `open` if the data can contain either more or fewer columns than the schema specifies

I've changed the algorithm for merging the `columns` array to take these options into account; that does mean some special handling of virtual columns.

I used the following examples to help guide me, which could be turned into test cases. Start with:

```
base metadata

A, B, X', Y'
```

`X'` and `Y'` are virtual columns, `A` and `B` are real columns. This is then merged into the following data, with the results listed

```
data1

A, B, C, X', Y'

 - closed = error
 - extension = A, B, C, X', Y'
 - restriction = error
 - open = A, B, C, X', Y'

data2

A, X', Y'

 - closed = error
 - extension = error
 - restriction = A, X', Y'
 - open = A, B, X', Y'

data3

A, B

 - closed = A, B, X', Y'
 - extension = A, B, X', Y'
 - restriction = A, B, X', Y'
 - open = A, B, X', Y'

data4

A, B, C

 - closed = error
 - extension = A, B, C, X', Y'
 - restriction = error
 - open = A, B, C, X', Y'

data5

A

 - closed = error
 - extension = error
 - restriction = A, X', Y'
 - open = A, B, X', Y'

data6

A, B, X', Y', Z'

 - closed = A, B, X', Y', Z'
 - extension = A, B, X', Y', Z'
 - restriction = A, B, X', Y', Z'
 - open = A, B, X', Y', Z'

data7

A, B, Z'

 - closed = A, B, Z', X', Y'
 - extension = A, B, Z', X', Y'
 - restriction = A, B, Z', X', Y'
 - open = A, B, Z', X', Y'
```

### CODE REVIEW

**Comment by gkellogg** [comment]
This looks good, but does complicate column merge a lot. Perhaps the group should discuss #14 on the call to determine if the more flexible validation modes are worth the added complexity.

**Comment by iherman** [comment]
Why do we need these categories?

After all (I would think) validation should occur on the post-merged and expanded metadata (ie, all merges are done and, at least conceptually, the default additions are made), meaning that the number of columns in the data must match the number of non-virtual columns in the metadata; if the metadata contains less columns then the expansion step would add the missing ones with the default column names anyway. Ie, the only error condition seems to be when the metadata contains _more_ non-virtual columns, and that seems to be an error to me no matter what.

Ivan

> On 17 Feb 2015, at 24:26 , Jeni Tennison notifications@github.com wrote:
> 
> fixes #14
> 
> I've ended up introducing four validation modes:
> 
>   • closed if the columns in a schema and the data file must match
>   • extension if the data is allowed to contain more columns than the schema specifies
>   • restriction if the data is allowed to contain fewer columns than the schema specifies
>   • open if the data can contain either more or fewer columns than the schema specifies
> I've changed the algorithm for merging the columns array to take these options into account; that does mean some special handling of virtual columns.
> 
> I used the following examples to help guide me, which could be turned into test cases. Start with:
> 
> base metadata
> 
> A, B, X', Y'
> 
> X' and Y' are virtual columns, A and B are real columns. This is then merged into the following data, with the results listed
> 
> data1
> 
> A, B, C, X', Y'
> - closed = error
> - extension = A, B, C, X', Y'
> - restriction = error
> - open = A, B, C, X', Y'
> 
> data2
> 
> A, X', Y'
> - closed = error
> - extension = error
> - restriction = A, X', Y'
> - open = A, B, X', Y'
> 
> data3
> 
> A, B
> - closed = A, B, X', Y'
> - extension = A, B, X', Y'
> - restriction = A, B, X', Y'
> - open = A, B, X', Y'
> 
> data4
> 
> A, B, C
> - closed = error
> - extension = A, B, C, X', Y'
> - restriction = error
> - open = A, B, C, X', Y'
> 
> data5
> 
> A
> - closed = error
> - extension = error
> - restriction = A, X', Y'
> - open = A, B, X', Y'
> 
> data6
> 
> A, B, X', Y', Z'
> - closed = A, B, X', Y', Z'
> - extension = A, B, X', Y', Z'
> - restriction = A, B, X', Y', Z'
> - open = A, B, X', Y', Z'
> 
> data7
> 
> A, B, Z'
> - closed = A, B, Z', X', Y'
> - extension = A, B, Z', X', Y'
> - restriction = A, B, Z', X', Y'
> - open = A, B, Z', X', Y'
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/w3c/csvw/pull/225
> 
> Commit Summary
> 
>   • introduced validation modes
> File Changes
> 
>   • M metadata/index.html (64)
>   • M syntax/index.html (4)
> Patch Links:
> 
>   • https://github.com/w3c/csvw/pull/225.patch
>   • https://github.com/w3c/csvw/pull/225.diff
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by JeniT** [comment]
@iherman as far as I can figure it, the only place where we can add validation around the number of columns in the data is in the merge algorithm around the column descriptions (because the way the algorithm works now, the columns in the data are extracted to create the 'embedded metadata'). That means whatever validation/algorithm that we apply to check the data against the metadata must also work when merging metadata.

It would be incredibly useful if people could take the examples that I have above and explain how they imagine it should work, just by indicating what should happen in each case if there aren't any modes at all, or with the modes that you think we should support. I think people are operating under different assumptions about what's 'obvious' here.

**Comment by iherman** [comment]
> On 17 Feb 2015, at 13:42 , Jeni Tennison notifications@github.com wrote:
> 
> @iherman as far as I can figure it, the only place where we can add validation around the number of columns in the data is in the merge algorithm around the column descriptions (because the way the algorithm works now, the columns in the data are extracted to create the 'embedded metadata'). That means whatever validation/algorithm that we apply to check the data against the metadata must also work when merging metadata.

I agree

> It would be incredibly useful if people could take the examples that I have above and explain how they imagine it should work, just by indicating what should happen in each case if there aren't any modes at all, or with the modes that you think we should support. I think people are operating under different assumptions about what's 'obvious' here.

As we said at the F2F (I am not sure about the terminology we used) the metadata merging step is conceptually a sequence of three different steps:
- normalization of each metadata
- merge all the metadata resulting in an 'overall' metadata
- 'expand' the resulting 'overall' metadata per our different defaults, eg, adding "name" where they are missing and the like

My assumption is that the validation happens on the merged metadata. And again my assumption is that, e.g., missing column descriptions are added during the expansion phase.

That assumption may be wrong.

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by JeniT** [comment]
OK, good, so @iherman what do you think should happen when there is metadata that says the columns are A, B, C and you're merging in other metadata that says that they are D, E, F. How should the merge behave? Are there errors?

Now, what should happen in the cases where the metadata being merged in contains A, B, X', Y' (where X' and Y' are virtual columns) and the data/metadata that it's being merged into contains:
- A, B (ie the real columns match exactly)
- A, B, C (ie there's an additional real column)
- A (ie there are fewer real columns)
- A, B, C, X', Y' (ie there's an extra real column and repetition of the virtual columns)
- A, X', Y' (ie there's a missing column and repetition of the virtual columns)
- A, B, X', Y', Z' (ie the definitions are the same except there's an additional virtual column)
- A, B, Z' (ie the real columns are the same but there's a new, different, virtual column)

Which of these are errors? What's the result of the merge in the cases that aren't errors?

**Comment by gkellogg** [comment]
Working off of @JeniT's examples the way I think it works now (at least how my processor implements it):

```
base metadata

A, B, X', Y'
```

`X'` and `Y'` are virtual columns, `A` and `B` are real columns. This is then merged into the following data, with the results listed

```
data1

A, B, C, X', Y'

> - closed = error
> - extension = A, B, C, X', Y'
> - restriction = error
> - open = A, B, C, X', Y'
- existing = error
```

The existing spec will not match `X'` and `C` as the column name/titles don't match. My implementation will use actual data in the columns for `X'` and `Y'`. The spec text could be improved to either make this an explicit error, or add virtual columns _as necessary_.

```
data2

A, X', Y'

> - closed = error
> - extension = error
> - restriction = A, X', Y'
> - open = A, B, X', Y'
- existing = error
```

The existing spec will not match `B` and `X'` as the column name/titles don't match.

```

data3

A, B

> - closed = A, B, X', Y'
> - extension = A, B, X', Y'
> - restriction = A, B, X', Y'
> - open = A, B, X', Y'
- existing = A, B, X', Y'
```

My implementation will use actual data in the columns for `X'` and `Y'`. The spec text could be improved to either make this an explicit error, or add virtual columns _as necessary_.
data4

```

A, B, C

> - closed = error
> - extension = A, B, C, X', Y'
> - restriction = error
> - open = A, B, C, X', Y'
- existing = error
```

The existing spec will not match `X'` and `C` as the column name/titles don't match.

```
data5

A

> - closed = error
> - extension = error
> - restriction = A, X', Y'
> - open = A, B, X', Y'
- existing = A, B, X', Y'
```

This is an area that needs to be refined, as the metadata describes columns that do not exist in the source. My implementation would see that it needs a total of four columns, and would extend the row accordingly, using a `null` value (I assume just one value, but probably the first defined value for `null` if there are multiple). This could also be an _error_, as the expected column count does not match. Requires spec text.

```
data6

A, B, X', Y', Z'

> - closed = A, B, X', Y', Z'
> - extension = A, B, X', Y', Z'
> - restriction = A, B, X', Y', Z'
> - open = A, B, X', Y', Z'
- existing = A, B, X', Y', Z'
```

As X', Y', and Z' are all actual columns in the data, they will match the defined A, B, X', and Y', but use actual data in the columns rather than defaults. Z' is added as embedded metadata.

```
data7

A, B, Z'

> - closed = A, B, Z', X', Y'
> - extension = A, B, Z', X', Y'
> - restriction = A, B, Z', X', Y'
> - open = A, B, Z', X', Y'
- existing = error
```

The existing spec will not match `X'` and `Z'` as the column name/titles don't match.

**Comment by JeniT** [comment]
And how _should_ it work?

#14 called for both "open" and "closed" validation, but with a definition of "open" that meant "every column in the data must be present in the metadata", not that "every column in the schema must be present in the data". The trouble with that is that it means that you can't override faulty metadata with user-defined metadata, given the way in which we've defined things.

The simplest thing would be to require all real columns to be present exactly as defined in the metadata, and for all virtual columns to appear in higher-priority (eg user-defined) metadata exactly in the same order, if they appear at all, but enabling extension. I think that means, given a base metadata of A, B, X', Y' (where X' and Y' are virtual columns):
- A, B, C, X', Y' => error
- A, X', Y' => error
- A, B => A, B, X', Y'
- A, B, C => error
- A => error
- A, B, X', Y', Z' => A, B, X', Y', Z'
- A, B, Z' => error

Since this matches with what @gkellogg says should happen "currently", I'll redraft with that as the goal.

**Comment by iherman** [comment]
(I did this _without_ looking at Gregg's subsequent comments to avoid being influenced at this point; influencing may come later!)

I presume, in all cases, the equality of the column descriptions, ie, the A-s below, is meant to be the way we describe in the merge algorithm, ie, either the names are equal (if they exist) or the titles intersect... Although, at this moment, I do not know how we define the equality of two virtual column descriptions. To be defined, I presume.

I use merge(A) below to signify the merge of the column descriptions identified by A.

> On 17 Feb 2015, at 18:24 , Jeni Tennison notifications@github.com wrote:
> 
> OK, good, so @iherman what do you think should happen when there is metadata that says the columns are A, B, C and you're merging in other metadata that says that they are D, E, F. How should the merge behave? Are there errors?

Yes if (in this case) the number of columns in the data is actually smaller than 6. 

> Now, what should happen in the cases where the metadata being merged in contains A, B, X', Y' (where X' and Y' are virtual columns) and the data/metadata that it's being merged into contains:
> 
>   • A, B (ie the real columns match exactly)

merge(A), merge(B), X', Y'
no error

>   • A, B, C (ie there's an additional real column)

merge(A), merge(B), C, X', Y'
error if the number of columns in the data < 3

>   • A (ie there are fewer real columns)

merge(A), B, X', Y'
no error

>   • A, B, C, X', Y' (ie there's an extra real column and repetition of the virtual columns)

merge(A), merge(B), C, merge(X'), merge(Y')
error if the number of columns in the data < 3

>   • A, X', Y' (ie there's a missing column and repetition of the virtual columns)

merge(A), B, merge(X'), merge(Y')
no error

>   • A, B, X', Y', Z' (ie the definitions are the same except there's an additional virtual column)

merge(A), merge(B), merge(X'), merge(Y'), Z'
no error

>   • A, B, Z' (ie the real columns are the same but there's a new, different, virtual column)
> Which of these are errors? What's the result of the merge in the cases that aren't errors?

merge(A), merge(B), X', Y', Z'
no error

(Note the fact that if the data contains a first row for the titles (by far the most widespread case) that will automatically lead to an error if any of the metadata tries to introduce another column that is not flagged as virtual: indeed, that metadata is the highest priority one after the user metadata.)

Ivan

P.S. Now I can look at Gregg's:-)

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C 
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by iherman** [comment]
> On 17 Feb 2015, at 22:16 , Jeni Tennison notifications@github.com wrote:
> 
> And how should it work?
> 
> #14 called for both "open" and "closed" validation, but with a definition of "open" that meant "every column in the data must be present in the metadata", not that "every column in the schema must be present in the data". The trouble with that is that it means that you can't override faulty metadata with user-defined metadata, given the way in which we've defined things.
> 
> The simplest thing would be to require all real columns to be present exactly as defined in the metadata, and for all virtual columns to appear in higher-priority (eg user-defined) metadata exactly in the same order, if they appear at all, but enabling extension.

Putting aside the virtual columns for a moment: what you seem to suggest (but I may misunderstand) is that all metadata should contain _exactly_ the number of column descriptions as there are columns in the data. This would also mean that we do not need the whole identification procedure that we define (names being equal, or titles intersect) for the merge algorithm (because we merge by indexes) although such a check for the validation is probably needed. I can very well live with that, if this is what you meant. Actually, I would favour that.

As for the virtual columns: I guess again what you mean is that the array of virtual columns are either merged, if they are present on the higher priority metadata, or are concatenated to the array of virtual columns. That works. (Note, b.t.w., that the order of virtual columns is irrelevant, because they are essentially RDF triples whose order is not defined, so this is only a matter of describing the merge.) 

Ivan

> I think that means, given a base metadata of A, B, X', Y' (where X' and Y' are virtual columns):
> 
>   • A, B, C, X', Y' => error
>   • A, X', Y' => error
>   • A, B => A, B, X', Y'
>   • A, B, C => error
>   • A => error
>   • A, B, X', Y', Z' => A, B, X', Y', Z'
>   • A, B, Z' => error
> Since this matches with what @gkellogg says should happen "currently", I'll redraft with that as the goal.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C 
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Pull request merged**
