### PR TITLE
Add information on virtual columns.

### LINKED ISSUE #179: Do we need "virtual" ("phantom") columns, i.e., columns with their own and separate 'aboutUrl' value?
This is a spin-off of issue #96 (and it allows closing #96).

The metadata allows for a `aboutUrl` template, that defines, both for the JSON and RDF mappings, the url for a row. This url binds together all cells in a row; for JSON, this manifests itself in an object for each row, in RDF as a series of triples sharing a common subject. As such, the natural place for the `aboutUrl` is the `tableSchema` level.

The question is whether it is allowed to define `aboutUrl` for an individual column, i.e., create a separate url for a specific cell in a role ("phantom" columns). If it is allowed, the question is how it translates in JSON and RDF.

@gkellogg has proposed a structure in https://github.com/w3c/csvw/issues/96#issuecomment-71960586. However, this looks fairly arbitrary to me. It makes sense for the data below, of course, but if I can have a separate subject for a column, well, a cell (by virtue of using a template) then those triples or JSON objects may, logically, be completely 'outside' the basic row structure (therein lies the complication!). Ie, we could simple remove the "row" relationship and have each columns and triples being loose, or having those out-of-band objects and triples being completely loose somehow tied to the table, or... I am not sure. 

We need to look at the use cases and see what structures there is (if any) for those cases to see where we go with this. At the moment, I am more in favor of disallowing `aboutUrl` in a column.

### PR DESCRIPTION
**Pull request by gkellogg**
This fixes #179.

### CODE REVIEW

**Comment by JeniT** [comment]
Are you planning on adding handling of the merge algorithm for virtual columns in a separate PR? I think there need to be some examples added too. It's not clear at the moment why you'd need a virtual column (why adding cells to a row is useful).

**Comment by gkellogg** [comment]
I don't believe there are any changes necessary to the merge algorithm; unless a virtual column happens to be named the same as a new column that exists in the file, the existing merge algorithm will work. A small change could ensure that if there is a column match that the value of `virtual` MUST be the same, but otherwise, it will work as with other atomic properties, which I think is okay.

An example is needed, and I thought I'd get to that later, but probably best to include in this PR. I'll add one.

**Comment by JeniT** [comment]
What are the **string values** and **cell values** of cells in virtual columns? I suggest that the string value is always an empty string and the cell value is handled accordingly (ie usually it will then be equal to the `default` value). A note or something that mentions this would make it clear, or through an example perhaps that has:

```
{
  "name": "type",
  "virtual": true,
  "default": "Person"
}
```

**Comment by gkellogg** [comment]
@JeniT that is my interpretation. I had previously put something in the syntax document to describe virtual columns and how empty cells are added to the annotated table as necessary, but that was lost when merging work done in flight. I've attempted to re-create it. Note that some of it is in the informal table processing section. Please improve if it doesn't fit your idea of how this should be described.

**Comment by iherman** [comment]
I wonder whether a small additional rule wouldn't make the life of implementers a bit easier: that virtual columns must follow the 'real' ones, rather than being mixed. That would allow implementers to go through the columns in parallel with the data without matching the indexes all the time, and then take care of the virtual columns separately. (I have not tried this, just running it in my head). If we agree to do that, a minor adjustment of either the post-merge normalization or the merge algorithm may be necessary...

Ivan

> On 15 Feb 2015, at 23:04 , Gregg Kellogg notifications@github.com wrote:
> 
> I don't believe there are any changes necessary to the merge algorithm; unless a virtual column happens to be named the same as a new column that exists in the file, the existing merge algorithm will work. A small change could ensure that if there is a column match that the value of virtual MUST be the same, but otherwise, it will work as with other atomic properties, which I think is okay.
> 
> An example is needed, and I thought I'd get to that later, but probably best to include in this PR. I'll add one.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by JeniT** [comment]
@iherman The text that @gkellogg has suggested in this PR already says that the virtual columns have to go at the end.

@gkellogg I've just expanded the example a little. See if you're happy with it.

**Comment by iherman** [comment]
> On 16 Feb 2015, at 11:19 , Jeni Tennison notifications@github.com wrote:
> 
> @iherman The text that @gkellogg has suggested in this PR already says that the virtual columns have to go at the end.

Ah ok! Thanks for the info.

Ivan

> @gkellogg I've just expanded the example a little. See if you're happy with it.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Pull request merged**
