### PR TITLE
primer: geospatial data

### LINKED ISSUE #795: Geometry datatype with tabular data metadata file
Has any consideration been given to supporting geometry datatypes (points, lines, polygons + spatial reference system) within the standards for CSV on the web? Either using GeoJSON or OGC WKT geometry encoding formats would be good.

I know there is a Spatial Data on the Web Working Group, but I couldn't find any commentary about this issue.

### PR DESCRIPTION
**Pull request by JeniT**
fixes #795

### CODE REVIEW

**Comment by palmerj** [comment]
Yes I agree with @rouault we need to be able to specify the spatial reference system for the column. Also the BNF for WKT need to conform with the OGC specification.

**Comment by jachym** [comment]
I Agree with @rouault about WKT

I would resign about coordinate system information: just stick to WGS84. CSV is supposed to be KISS, right?

**Comment by palmerj** [comment]
@jachymI I think there are a couple of use cases (which seem to align with the CSVW WIP use cases https://www.w3.org/2013/csvw/wiki/Use_Cases) where this standard should support non-WGS84 geographic coordinates:
- public national land registry data
- national mapping datasets

In both of these cases users will most likely want the data in national grid coordinates. This is because users often want to perform distance and areas calculations, and geographic coordinates make things much more difficult. Either the publisher has to transform the source data from the national grid to WGS84, and then the user has to transform the download back to the national grid; or by the user has to execute more expensive geodetic calculations which would otherwise be much faster using grid coordinates. So IMHO we should at least support specifying the coordinate system when using WKT. But if we want to be consistent we could also extend this to GeoJSON as the specification does allow for it: http://geojson.org/geojson-spec.html. KML standard only allows for WGS84 geographic coordinates - so no question on this format.

**Comment by JeniT** [comment]
@rouault @palmerj @jachym thank you for your comments on this. I've revised the text according to your comments.

Unfortunately I can't find a standard property for expressing coordinate reference systems that looks sturdy enough to recommend, so I've punted and added a note that says the Spatial Data on the Web WG should make recommendations in this area (/cc @6a6d74).

Could you take another look and see if there's anything more I should do? Thanks!

**Comment by palmerj** [comment]
Thanks @JeniT I would advocate @rouault suggestions of http://www.opengis.net/def/crs/EPSG/0/xxxx but specify that KML and GeoJSON enforce an axis order x,y order.

Thinking more about the approach of using custom datatypes, would it not be better for users and software implementers to consider making the geometry datatype part of the core CSVW standard? The approach of using custom datatypes is too ambiguous and open to too much interpretation, which will make widespread use hard. Also having a core datatype means the ability to add annotations such as the geometry "type" (i.e. point, linestring, polygon, multipoint, multilinestring, multipolygon, geometrycolumn) and the geometry's coordinates reference system "crs" (e.g http://www.opengis.net/def/crs/EPSG/0/4326). Also IMHO using WKT for the definition is the best fit for the CSV data because it is the most commonly used serialised text format for export and import out of database systems. e.g Oracle spatial, Informix, DB2, PostgreSQL etc. Maybe the main use case of x,y or lat/long point positions could be left to using number/double datatype. JSON and KML is mostly used in full XML or JSON documents, rather than being used as a fragment within plain text files such as CSV.

**Comment by iherman** [comment]
@palmerj, this is just an administrative response.

I think the discussion about geometry datatype in CSVW (or not) is not relevant for the primer at this point. I have therefore opened a separate issue (#828), essentially quoting your previous remark, and I think any ongoing discussion should happen there.

However, I have immediately labeled that issue as "Deferred to Version 2"; indeed, the core CSVW has been published as a Recommendation already, and this Working Group is closing down in a few weeks. Note that the discussion on CSVW in general continue in a [separate Community Group](https://www.w3.org/community/csvw/) which may discuss issues like this one, ie, issues for a _possible_ second version of the standard. It may be of interest for you to join that CG, actually!

**Comment by palmerj** [comment]
@iherman Thanks - makes sense. How will know when the new community group will come together for version 2?

**Comment by palmerj** [comment]
Hmm ok. That potentially makes it a lost opportunity to support a large growing domain.

**Comment by jachym** [comment]
@palmerj I'm fine with that, as long as there is already reference for having coordinate information in the data. 

But - what should be the use case of geo-data in CVS format? IMHO it's just exchange format, used for data transfer between two systems, not suited to be used directly. Therefore, no need for CRS definition. 

HOWEVER, praxis says, people will _always_ try to hack CRS info into formats, which are WGS84 explicit (KML, GeoJSON, ...), so having such possibility from the beginning makes sense.

Sorry, just commenting

**Comment by palmerj** [comment]
@jachym: Yes the primary use case I was thinking of was for a transfer format between systems. If we are talking about operational use then it's not appropriate. 

More and more we have customers that wanting better standards based format for the transfer for large data, that most system can just deal with. In NZ our cadastre and land registry data (https://data.linz.govt.nz/data/category/full-landonline-dataset/) actually has over 50% of it's downloads in CSV format. But because CSV had no clear standard we just went with the format that the GDAL/OGR exported (http://www.gdal.org/drv_csv.html), which has been hard work for non GDAL/OGR users.

**Pull request merged**
