### PR TITLE
Prepared the publishing snapshot setup for PR publication

### PR DESCRIPTION
**Pull request by iherman**
I have
- created the publishing snapshot folders
- modified the local-biblio.js with a provisional publication date of 24 November
- modified the original sources to use 'diff.html' as diff file, instead of 'diff-XXXXXXXX.html' (these dates are unnecessary in the final format, and just creates problem if we change the publication date

@gkellogg @JeniT please just a quick sanity check before merge...

### CODE REVIEW

**Comment by gkellogg** [comment]
Do we need to snapshot the implementation report?

**Comment by iherman** [comment]
> On 29 Oct 2015, at 07:41, Gregg Kellogg notifications@github.com wrote:
> 
> Do we need to snapshot the implementation report?

Good point. That should be done when we go to PR indeed. Let us do that on github with a separate snapshot, and I would change the redirection

Ivan

> —
> Reply to this email directly or view it on GitHub https://github.com/w3c/csvw/pull/771#issuecomment-152019332.

---

Ivan Herman, W3C
Digital Publishing Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
The specs currently reference http://www.w3.org/2013/csvw/tests/reports/index.html which is a redirect to http://w3c.github.io/csvw/tests/reports/index.html. I'll create the snapshot.

**Comment by iherman** [comment]
> On 29 Oct 2015, at 08:44, Gregg Kellogg notifications@github.com wrote:
> 
> The specs currently reference http://www.w3.org/2013/csvw/tests/reports/index.html http://www.w3.org/2013/csvw/tests/reports/index.html which is a redirect to http://w3c.github.io/csvw/tests/reports/index.html http://w3c.github.io/csvw/tests/reports/index.html. I'll create the snapshot.

Yep. So I will change the redirection for the /2013/… file (later, I am now on a F2F meeting)

Ivan

> —
> Reply to this email directly or view it on GitHub https://github.com/w3c/csvw/pull/771#issuecomment-152032519.

---

Ivan Herman, W3C
Digital Publishing Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
Otherwise, all they need is snapshots of the finished index.html files.

**Comment by iherman** [comment]
> On 29 Oct 2015, at 08:56, Gregg Kellogg notifications@github.com wrote:
> 
> Otherwise, all they need is snapshots of the finished index.html files.

You mean remove the redirection, and leave the github version the 'life' one? That can also work but… then the implementation report should include a reference to the life one.

Ivan

> —
> Reply to this email directly or view it on GitHub https://github.com/w3c/csvw/pull/771#issuecomment-152035100.

---

Ivan Herman, W3C
Digital Publishing Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
You'll notice the SoTD section of the implementation report includes a link to https://w3c.github.io/csvw/tests/reports/index.html for future updates to the report.

Regarding:

>  Otherwise, all they need is snapshots of the finished index.html files.

My comment was that, for example, publishing-snapshots/PR-syntax has no Overview.html yet; presumably that comes later.

**Comment by iherman** [comment]
Yes @gkellogg , the Overview.html comes later (by the editors). At this moment, I have just set up the scaffolding.

**Comment by iherman** [comment]
@gkellogg : I have created a new redirection from http://www.w3.org/2013/csvw/implementation_report.html to http://w3c.github.io/csvw/publishing-snapshots/PR-earl/earl.html, this is what we will use in the PR transition. I left the other redirection in place; actually, it is the whole of csvw/tests which is redirected to github, not only that file.

**Pull request merged**
