### PR TITLE
test107 should be warning not negative test

### PR DESCRIPTION
**Pull request by JeniT**
The tableSchema property is invalid, which means a warning is generated
and it’s treated like an empty object. All the properties of
tableSchema are optional, so this doesn’t generate any errors.

### CODE REVIEW

**Comment by gkellogg** [comment]
Yes, I see that these should be warnings, except for validation. Validation needs to be an error because of the following:

>  if TM is not compatible with EM validators **must** raise an error, other processors **must** generate a warning and continue processing.

Also, the property names used would be based on the Titles, rather than names, with percent encoding.

Merge if you agree.

**Comment by gkellogg** [comment]
Also @JeniT, look at the last commit. This is consistent with merging annotations from embedded metadata. Metadata is incompatible, but this is now a warning, and consequently the "Use the metadata TM to add annotations to the tabular data model T" clause causes the title to be pulled in. If you disagree, this has implications on where titles come from in 107.

**Comment by JeniT** [comment]
OK, I see the reason why it's an error when validating.

I don't see where it says that annotations from `EM` are merged into `TM` (cf your last commit) however, so don't think that those changes are correct.

**Comment by gkellogg** [comment]
You're right, I was mis-reading that; I'll need to go back. I think this would imply that 107 has no column names other than `_col.n`.

**Comment by gkellogg** [comment]
@JeniT: this is my interpretation of what the output for test107 should be, as there are no titles to construct column names from. Commit if you agree.

**Pull request merged**
