### PR TITLE
Tried to simplify the JSON generation

### PR DESCRIPTION
**Pull request by iherman**
Did this by:
- separating the minimal and standard modes into separate sections
- calling out to the (common) algorithms for the generation of objects for a row and for nesting

This approach came from the discussion in #299

/Cc @gkellogg @6a6d74

### CODE REVIEW

**Comment by gkellogg** [comment]
Yes, I think separating the algorithms would make it much easier to follow.

**Comment by gkellogg** [comment]
A couple if issues here, some of which relate to the original algorithm:
- [x] "Generating of Objects" => "Generating Objects"
- [ ] Step 3.1 of Generating the Objects; `propertyUrl` is expanded in the metadata definition of [URI Template Properties](http://w3c.github.io/csvw/metadata/#uri-template-properties). These should be re-compacted to terms or prefixed names to be used as property names.
- [x] Step 3.2-3.4 of Generating the Objects say to _insert_ the value; some provision must be made if such a value already exists due to a previous cell using the same property.
- [x] In Generating Nested Objects, there is the following statement: "referred to once and only once by another object Sk through a reference originating from an `aboutUrl` value". Should that be `valueUrl`?
- [ ] In Generating Nested Objects, when looking for values to substitute, these should be values generated from `valueUrl` rather than a cell value which was a literal.

**Comment by iherman** [comment]
> On 14 Mar 2015, at 20:25, Gregg Kellogg notifications@github.com wrote:
> 
> A couple if issues here, some of which relate to the original algorithm:
> 
>  "Generating of Objects" => "Generating Objects"
>  Step 3.1 of Generating the Objects; propertyUrl is expanded in the metadata definition of URI Template Properties. These should be re-compacted to terms or prefixed names to be used as property names.
>  Step 3.2-3.4 of Generating the Objects say to insert the value; some provision must be made if such a value already exists due to a previous cell using the same property.
>  In Generating Nested Objects, there is the following statement: "referred to once and only once by another object Sk through a reference originating from an aboutUrl value". Should that be valueUrl?
>  In Generating Nested Objects, when looking for values to substitute, these should be values generated from valueUrl rather than a cell value which was a literal.
> For the last remarks: as I put into the issues: that is just a placeholder, we know that must be rewritten.

Ivan

**Comment by gkellogg** [comment]
These might be created as issues, and resolved in the branch to be pulled. Subsequent commits to that branch will be added to this PR. However, I think it's easier just to push new commits to this branch, and check off each point which is raised in the comment above, unless you feel a new issue is warrented.

**Comment by gkellogg** [comment]
Another thing on generating the object:
- [ ] If `propertyUrl` is `rdf:type`, use `@type` for name, Compact values using the same mechanism for propertyUrl compaction.

**Comment by iherman** [comment]
> On 14 Mar 2015, at 20:25 , Gregg Kellogg notifications@github.com wrote:
> 
> A couple if issues here, some of which relate to the original algorithm:
> 
>   •  "Generating of Objects" => "Generating Objects"

Done

>   •  Step 3.1 of Generating the Objects; propertyUrl is expanded in the metadata definition of URI Template Properties. These should be re-compacted to terms or prefixed names to be used as property names.

I wonder how to do that properly, and whether this is not something to be described more generally somewhere. Indeed, compacting the URI may be relevant for aboutUrl-s and valueUrl-s as well; after all, if we do use compacted values, they may look better. Of course, propertyUrl-s are the place where it occurs the most often, but may also occur for the other two. Ie, wouldn't it be better to refer to this in the model document, saying that the value returns a full URI as well as a compacted URI when possible? Conversions may then use what they want.

>   •  Step 3.2-3.4 of Generating the Objects say to insert the value; some provision must be made if such a value already exists due to a previous cell using the same property.

Added. I decided to add a separate mini algorithm-kind list to make very clear what we mean by 'insert' in this case, rather then repeating the same steps

>   •  In Generating Nested Objects, there is the following statement: "referred to once and only once by another object Sk through a reference originating from an aboutUrl value". Should that be valueUrl?

Oops, yes.

>   •  In Generating Nested Objects, when looking for values to substitute, these should be values generated from valueUrl rather than a cell value which was a literal.

I think that is part of the general description of the algorithm, so I have not changed anything. I may create a separate branch, starting from this branch, which gives the algorithm description based on [my version](https://github.com/w3c/csvw/issues/299#issuecomment-78486015) just to have it handy at hand if we need it:-) But I do not change anything on the present PR, let us see if @6a6d74 is o.k. with it first.

**Comment by iherman** [comment]
> On 14 Mar 2015, at 22:49 , Gregg Kellogg notifications@github.com wrote:
> 
> Another thing on generating the object:
> 
>   •  If propertyUrl is rdf:type, use @type for name, Compact values using the same mechanism for propertyUrl compaction.

See my [previous reply](https://github.com/w3c/csvw/pull/362#issuecomment-80943074): I think the compaction should be described at one place, then this can be incorporated. So not done for the moment.

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
Because of the differences in how values and properties are compacted (with or without being like `@vocab` in JSON-LD), it would be difficult to do this as part of the cell model. However, the algorithm is pretty simple, and I can create a section in CSV2JSON on compacting IRIs, but probably best to wait until outstanding PRs are merged.

Basically, for properties and values of `@type`:
- If the URL exactly matches a term in the context, replace the URL with that term.
- Otherwise, if the the context has a term who's URI definition is a prefix of the URL, replace the URL with a prefixed name formed from the term, a ':', and the remainder of the URL after the URL prefix.

For all other values which are a URL:
- If the the context has a term who's URI definition is a prefix of the URL, replace the URL with a prefixed name formed from the term, a ':', and the remainder of the URL after the URL prefix.

Note that this does not do any document-relative compaction of values.

**Comment by iherman** [comment]
Hm. I do not really understand why there would be a difference. We do not have a @vocab in the metadata; the compaction of the URI-s are the same everywhere and are based exclusively on the predefined prefixes that are known in advance. It is of course a question whether this would be useful for RDF (probably not), but may be for other conversions.

Also, Do we allow for fragmentbid-s or URI-s with query parts to be compacted? I guess probably yes, but this should be made clear...

Ivan

---

Ivan Herman
Tel:+31 641044153
http://www.ivan-herman.net

(Written on mobile, sorry for brevity and misspellings...)

**Comment by gkellogg** [comment]
Properties and @type are vocabulary-relative, @id is document-relative. @id cannot take a term as a value, only a URI or prefixed name. Properties and @type can take a type (obviously, as intended for properties in particular), or a URI or prefixed name. A relative URL in property/@type is relative to @vocab, if defined. On @id it's relative to the document. For the details, see JSON-LD.

As a result, a value of a property or @type can compact to a term, but not an @id (or other use of a valueUrl). That's just the way it is. We could of course, not compact to terms at all, in which case if we had `http://www.w3.org/ns/csvw/Table`, it would compact to 'Table:`rather than just`Table`, but that would be odd.

Currently, I don't specify compacting URLs to generally be document relative (CSV2JSON has a special case for this). But, there's no reason that fragment-ids or query parameters would be excluded here. If we choose to compact to relative URIs (not sure there's a need for this), then it would simply be by removing the document URL prefix, if it ends in "/" or "#"; otherwise, probably not worth doing. I'm not sure we really need to do this, though.

**Comment by iherman** [comment]
I really believe this is a separate issue, though. I will generate one.

Ivan

> On 16 Mar 2015, at 05:13 , Gregg Kellogg notifications@github.com wrote:
> 
> Properties and @type are vocabulary-relative, @id is document-relative. @id cannot take a term as a value, only a URI or prefixed name. Properties and @type can take a type (obviously, as intended for properties in particular), or a URI or prefixed name. A relative URL in property/@type is relative to @vocab, if defined. On @id it's relative to the document. For the details, see JSON-LD.
> 
> As a result, a value of a property or @type can compact to a term, but not an @id (or other use of a valueUrl). That's just the way it is. We could of course, not compact to terms at all, in which case if we had http://www.w3.org/ns/csvw/Table, it would compact to 'Table:rather than justTable`, but that would be odd.
> 
> Currently, I don't specify compacting URLs to generally be document relative (CSV2JSON has a special case for this). But, there's no reason that fragment-ids or query parameters would be excluded here. If we choose to compact to relative URIs (not sure there's a need for this), then it would simply be by removing the document URL prefix, if it ends in "/" or "#"; otherwise, probably not worth doing. I'm not sure we really need to do this, though.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by iherman** [comment]
Added issue #365 for this; I believe we can proceed with the PR merge, if @6a6d74 agrees, and that issue can be taken separately.

/Cc @6a6d74

**Comment by 6a6d74** [comment]
@gkellogg, @iherman ... apologies for the delay :-(

Having reviewed @iherman's proposal I am content with the restructuring; noting the following caveats:
i) the nesting of objects remains unresolved - this is being dealt with in ISSUE #299 
ii) the need for URL compaction - this is being dealt with in ISSUE #365 

There are a few editorial changes that I would like to add - but I will do this with a separate PR ... I feel the need to unblock this PR so that other discussions can proceed.

**Pull request merged**
