### PR TITLE
added non-core annotations on rows in conversions

### LINKED ISSUE #445: Row annotations in conversion specifications
The model document states that **rows** can have annotations. (Though the metadata document doesn't provide any official mechanism for giving rows annotations, an implementation could build a model in which a row had annotations, eg by interpreting `notes`.)

I think the conversion specifications should state that in **standard mode**, all non-core row annotations are copied onto the **csvw:Row** objects in just the same way as non-core table annotations are copied onto tables.

### PR DESCRIPTION
**Pull request by JeniT**
fixes #445

### CODE REVIEW

**Comment by iherman** [comment]
I am a little bit bothered by the fact that the handling of these core annotations refer to the json-ld handling that we define in the metadata document. Ideally, there should be no dependency on the metadata document in the conversions, only on the model.

At the moment, the model only says:

> Columns MAY in addition have any number of other annotations, such as a description. When originating from [tabular-metadata], these annotations arise from common properties defined on table group descriptions within metadata documents.

i.e., the common annotations may have other formats that are not abiding to the json-ld restrictions.

I am not sure, however, how to handle this. Maybe the conversion documents should have the same caveats as the syntax ("When originating from…"), meaning that if other specifications come forward with other types of annotations, they are supposed to make clear how those annotations are to be transformed for JSON and/or for RDF.

**Comment by gkellogg** [comment]
It looks like the reference is to the JSON-LD-to-JSON section within the csv2rdf document, so there is no reference to the metadata document, at least as introduced by this commit.

Perhaps we need something in the model document that says that non-core annotations MUST have the lexical form of our JSON-LD subset. That might require that the definition move to the model document.

**Comment by JeniT** [comment]
I have simply copied the wording around the handling of notes and non-core annotations when they appear on tables, so haven't introduced anything new here wrt the handling of those values.

The model document already says "The values of these annotations may be lists, structured objects, or atomic values." This could be expanded if you like, though I'd suggest we don't focus on lexical forms within the abstract model.

**Comment by iherman** [comment]
I agree with @JeniT  that lexical details should not be part of the model (my mental analogy is the xml infoset document...). That is why I proposed to put some caveats in the conversion document.

**Pull request merged**
