### PR TITLE
Test100 should be a warning, not an error.

### PR DESCRIPTION
**Pull request by gkellogg**
@JeniT, I think this was mis-catagorized, and should generate warnings not errors unless validating.

### CODE REVIEW

**Comment by JeniT** [comment]
I disagree. The `columns` property doesn't hold an array, and therefore defaults to an empty array. The schemas are thus incompatible because the schema expects no columns whereas the data actually contains five. When validating, it's an error if there's not schema compatibility.

**Comment by gkellogg** [comment]
6.6 Validating Tables in the model document says validators MUST raise an error.

As you say, if the value of `columns` doesn't match, it is set to an empty array, and it certainly is not compatible, but processing continues, and data is generated, so in my view the processor issues a warning. If an error is generated when trying to generate RDF or JSON, no output is expected. This is also consistent with [Test127](http://w3c.github.io/csvw/tests/#manifest-json#test127), which is incompatible but issues warnings for RDF and JSON.

**Comment by JeniT** [comment]
OK, I see the change here only affects the JSON/RDF generation, so I think it's fine.

**Comment by 6a6d74** [comment]
@JeniT, seeing this relating to the CSV2RDF / CSV2JSON ... is there any
need for modifications to the related docs? Jeremy

**Pull request merged**
