### PR TITLE
Update implicit files used on test034 & test035.

### PR DESCRIPTION
**Pull request by gkellogg**
Fixes #479.

### CODE REVIEW

**Comment by gkellogg** [comment]
@6a6d74, it's a matter of updating the `implilcit` extra parameter in the manifest.cv and re-running mk_manifest.rb, FWIW.

**Comment by 6a6d74** [comment]
@gkellogg - I've removed the unnecessary test03n/junior-roles.json schema description (both the file and updated `manifest.csv`). However, I think my ruby installation is busted as I get an error when I run `mk_manifest.rb`.

Can you check what I've done and then rebuild the manifests please. 

Merge if you're happy.

**Comment by gkellogg** [comment]
I thought I had removed those files, but something must have happened on my end.

Running mk_manifest.rb may simply require installing gems. The only relatively non-standard gem used is "haml", and a `gem install haml` should be all that's required. I've taken care of it, and it's fairly easy to do. However, I should probably add something to the README on how to set up Ruby.

**Comment by 6a6d74** [comment]
yep. `haml` was the one I got a complaint about. Thanks ...

**Pull request merged**
