### PR TITLE
added @gkellogg as author on csv2rdf

### PR DESCRIPTION
**Pull request by 6a6d74**

### CODE REVIEW

**Comment by 6a6d74** [comment]
@JeniT - please merge if you're content with this change

**Comment by gkellogg** [comment]
Can't do it on csvw repo, apparently, but local-biblio.js should be updated too.

**Comment by iherman** [comment]
> On 10 Mar 2015, at 15:24 , Gregg Kellogg notifications@github.com wrote:
> 
> Can't do it on csvw repo,

??? What is it you cannot do?

Ivan

> apparently, but local-biblio.js should be updated too.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by gkellogg** [comment]
There are merge conflicts, and the PR comes from @6a6d74's repo, so I can't fix the problems on his repo, without doing a separate PR.

(Aside: IMO, we should do all work on branches off of http://github.com/w3c/csvw rather than in separate Repo forks to simplify issues such as this.).

**Comment by JeniT** [comment]
If @gkellogg's editing then he should be listed as an editor; I'm happy for the merge to go ahead when the conflicts are resolved :)

**Comment by JeniT** [comment]
+1 @6a6d74 you should create branches within the csvw repo rather than having your own fork; it would mean that we could help in situations like these

**Comment by iherman** [comment]
> On 10 Mar 2015, at 16:05, Gregg Kellogg notifications@github.com wrote:
> 
> There are merge conflicts, and the PR comes from @6a6d74's repo, so I can't fix the problems on his repo, without doing a separate PR.

Ah, ok. I understand now

> (Aside: IMO, we should do all work on branches off of http://github.com/w3c/csvw rather than in separate Repo forks to simplify issues such as this.).

+1

Ivan

**Comment by 6a6d74** [comment]
@JeniT - you're right ... should have kept things in csvw repo. Apologies to all.

**Comment by 6a6d74** [comment]
now fixed; see PR #348

**Pull request closed without merging**
