### PR TITLE
New version of the hiding buttons

### PR DESCRIPTION
**Pull request by iherman**
By adding a separate css file and some editing the annotation hiding now works with printing, too.

### CODE REVIEW

**Comment by iherman** [comment]
I have done what we agreed, and it works 90%. The remaining 10% caveat is that if the user plays with the buttons by turning things on and off, then the print will not result in the initial version. (See below.)

@6a6d74 : please have a look and make a merge if you think it is fine.

/Cc @6a6d74 @gkellogg 

P.S. If you are interested in the technical details: the problem is that, when printing, no JS code is automatically executed. That is why the `matchMedia` call does not work for this case. The current solution needs a mixture of css and javascript (hence the separate tiny css code); a complete solution would require that the browsers would react on `beforeprint` and `afterprint` events (whose handler could set an initial state and then turn the state back, so to say, to whatever the interrupted interaction was). Unfortunately, these two events are handled by IE; although they are said to be used by FF, they did not work for me, and there is no word for Chrome or Safari. We can improve that if things evolve in this respect...

**Comment by iherman** [comment]
Scrap my [previous comment](https://github.com/w3c/csvw/pull/381#issuecomment-84036003)! Having talked to @darobin on this, he had a better approach using only class changes instead of changes of `display`. And it works! Ie, the printing issue solved.

@6a6d74, please do a last sanity check and merge it if you feel fine about it. If you do, I guess #380 can be closed, too!

**Comment by gkellogg** [comment]
Looks good!

**Comment by 6a6d74** [comment]
Great stuff - exactly what we were after I think!

fixes #380 

Merging now

**Pull request merged**
