### PR TITLE
Html note updates

### LINKED ISSUE #802: How to handle mixed rows in HTML tables?
The HTML Note says that rows containing just `th` are header rows and those containing just `td` are data rows. I think that _all_ rows other than header rows should be data rows. Whether a cell is a `th` or a `td` in a data row is irrelevant.

### PR DESCRIPTION
**Pull request by gkellogg**
- Separate linking to metadata from embedding metadata within the HTML node.
- Revert from new layout style. Use normal bibliographic references.
- Describe embedding CSV data using script elements in HTML.
- Describe processing of caption, tbody, thead, and tfoot elements.
- Add section on embedded CSV.
- Allow processing of mixed rows containing both **td** and **th** elements. Fixes #802.
- Add best practice to avoid @colspan and @rowspan and suggest using a dialict description if necessary. Addresses #803.

I think this addresses the points raised in issues and in the last call. Let me know if I've missed anything, or you think that @colspan/@rowspan need mote explicit treatment; here they're dealt with using a Best Practice.

### CODE REVIEW

**Comment by iherman** [comment]
Minor:

Section 1.1
   one or more tabular data files https://www.w3.org/TR/tabular-data-model/#dfn-tabular-data-file can embedded in HTML -> one or more tabular data files https://www.w3.org/TR/tabular-data-model/#dfn-tabular-data-file can be embedded in HTML
  Meatadata  -> Metadata (title of the first example)

Section 1.2
   HTML ´link element -> HTML link element

Section 2.1

I do not really understand this statement:

   "thread, tbody, and tfoot elements are treated as if their content are child elements of the containing table element."

The sentence suggests that the cells within a thead (note the misspelling thread->thead, b.t.w.) and tfoot are treated the same way as normal cells for our purposes. As far as I remember, what we said is that the content of thead and tfoot are ignored. I guess  thead and tbody, should be added, alongside caption, to the previous bullet point

**Comment by gkellogg** [comment]
Thanks, I was on the road and more prone to typos.

I understood what we discussed to be to ignore `thead/tfoot/tbody` for processing purposes, and treat their content as if the did not exist, which I attempted to describe as such. The elements are not ignored, meaning that processing should proceed with their child elements. I'm open to a suggestion on how to re-phrase without loosing this meaning.

It would be reasonable to simply ignore `tfoot` and it's contents, but I thought it better to treat them all equivalently. `thead` would be a reasonable container for `th` elements, IMO.

**Comment by iherman** [comment]
Then we have a different recollection of the discussion... My recollection was that `thead` and `tfoot` are simply ignored, and the processing only takes `tbody` into account. But maybe I am wrong; I can see the point that `thead` could be considered as header cells. But I definitely think that `tfoot` (very rarely used in practice anyway) should be ignored.

Editorially, if we say `thead` is fine as content, then the only change is to move the referect to `tfoot` to the same bullet point as `caption` (which is also ignored). If `thead` is to be ignored, too, then it should also be moved.

Keeping `thead` or not: I can actually go either way.

**Comment by JeniT** [comment]
My opinion on this is that all the rows in the table should be considered, whether they are in `thead`, `tfoot` or `tbody`.

**Pull request merged**
