### PR TITLE
Adding an algorithm for nesting

### PR DESCRIPTION
**Pull request by iherman**
Adding the forest-tree based algorithm for nesting

### CODE REVIEW

**Comment by 6a6d74** [comment]
I am currently working on an amendment to this PR; I found the language quite difficult to understand so I am trying to rephrase things without messing up the algorithm ....

**Comment by iherman** [comment]
> On 17 Mar 2015, at 12:44 , Jeremy Tandy notifications@github.com wrote:
> 
> I am currently working on an amendment to this PR; I found the language quite difficult to understand so I am trying to rephrase things without messing up the algorithm ....

I am a mathematician by training, so I described it pretty much in mathematical terms... Let us see what you come up with! :-)

Ivan

> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by 6a6d74** [comment]
I'm an engineer by training; we'll try for something understandable :-)

**Comment by 6a6d74** [comment]
OK @iherman ... it's late in the day, but I think I have finally managed to rewrite the algorithm in terms I understand. I hope that this makes sense. See https://rawgit.com/w3c/csvw/b9cb28f0f72c7bb139628c39daf3182169a96669/csv2json/index.html for the HTML view.

(ps: hope it was OK to push on top of your branch to add to this PR; you can always revert if need be!)

**Comment by iherman** [comment]
@6a6d74 : I have gone through the changes, made some changes and committed back. The changes:
- Editorial issues: added a term for descendant, tightened up the definition of root, changed the usage of the term 'recurse' (which has a slightly different meaning in programming than the way it was used). These are not major.
- I have removed the reference to the open issue
- I removed the remark on nested objects at the 'return' of the algorithm; the point is that the algorithm returns the roots only and not the other objects, simply because the roots would include the nested objects already.
- You have added a reference to `null` and a branch whereby an object with a `null` id would be matched with an object that has no `valueUrl` defined. I think that is wrong: each object that has no `@id` has to keep its own, distinct identities (their ID is a blank node in RDF term...) and your changes would have lumped all of them together as a nested object. I think that is incorrect, so I removed that part.

If you agree with these changes, I would propose to merge the pull request, and consider this done!

**Comment by 6a6d74** [comment]
@iherman ... I'm happy with these amendments & will merge)

(wrt the `null` I was trying to catch the case for "unidentified" objects - where `aboutUrl` was not set ... however, it's pretty obvious that the intent is to catch these too so I'm happy with your amendment as it simplifies things.)

**Pull request merged**
