### PR TITLE
removed 3rd row from tree-ops.csv

### PR DESCRIPTION
**Pull request by 6a6d74**
and spotted a typo in the metadata doc: “trees-ops.csv”

### CODE REVIEW

**Comment by 6a6d74** [comment]
fixes #411

**Comment by 6a6d74** [comment]
@iherman asked whether the third row of `examples/tree-ops.csv` was a mistake. I've been though all the docs to find where it was referenced from - and agree with his conclusion: 3rd row was a mistake. 

Fixed in this PR.

@gkellogg - can you double check you're happy that there are no impacts for the syntax and metadata docs and merge if you're content?

**Comment by gkellogg** [comment]
Looking at the [City of Palo Alto](http://w3c.github.io/csvw/use-cases-and-requirements/#UC-PaloAltoTreeData) use case, I think the duplicate happened because the original had columns truncated.

I don't think it's critical that there be more than two rows, so this should be fine. Note that many tests use this and will also need to be updated to be consistent.

**Comment by 6a6d74** [comment]
@gkellogg - apologies for the knock on impact to the tests. the docs quite clearly talk about "two rows" in the `tree-ops.csv` file - so it needs updating. Please merge if/when you're content.

**Comment by gkellogg** [comment]
I was going to refactor the tests to use a common action file anyway; I'll do that in a separate branch.

**Pull request merged**
