### PR TITLE
Added URL Normalization section to data model, use for determining me…

### PR DESCRIPTION
**Pull request by gkellogg**
…tadata compatibility and discovery. For consistency, `link` property normalization includes URL normalization. Note the issue marker in the section to find a better way of describing the schemes for which scheme-based normalization should/must be defined.

This should affect tests, both by exploring cases of link-property normalization, metadata discovery and compatibility. #562.

### CODE REVIEW

**Comment by JeniT** [comment]
I'm not sure what to do here. I think that the basis of comparison should probably be whether they both parse into the same structure as defined in https://url.spec.whatwg.org/

**Comment by iherman** [comment]
We run into an administrative problem; can we, normatively, refer to the URL spec? I am afraid we cannot.

Ivan

> On 27 May 2015, at 09:48 , Jeni Tennison notifications@github.com wrote:
> 
> I'm not sure what to do here. I think that the basis of comparison should probably be whether they both parse into the same structure as defined in https://url.spec.whatwg.org/
> 
> —
> Reply to this email directly or view it on GitHub.

---

Ivan Herman, W3C
Digital Publishing Activity Lead
Home: http://www.w3.org/People/Ivan/
mobile: +31-641044153
ORCID ID: http://orcid.org/0000-0003-0782-2704

**Comment by JeniT** [comment]
waiting on discussion with TAG

**Comment by gkellogg** [comment]
@JeniT, note that one of the resolved conflicts was on special treatment of `datatype` strings during normalization, which will revert back along with other changes you're making regarding #543.

**Comment by gkellogg** [comment]
Also overlaps with PR #608.

**Comment by gkellogg** [comment]
I believe I resolved the overlap, so this should be good to go now.

**Pull request merged**
